### ISSUE TITLE
Octobot Discussion

### ISSUE THREAD

**Issue by juliandduque** [OctoConsulting/octobot#1]
Some things to keep in mind:

- Building the chat bot:
What platforms are we targeting?
Creating a chatbot is not too "complicated", implementing it however seems to be the issue. If we could centralize all our API calls to a single platform (like AWS) we can easily make all applications behave similarly as long as we can do a call to the server from were we deploy (alexa, mobile, web..)

**Comment by davidbzhao** [comment]
Going to append my ideas here
* If we can't use Microsoft Cognitive Services like I think was mentioned at the presentation, we're going to need to find another tool to generate the q/a bot (AWS might have one) or just try to make our own
* RocketChat has decent docs on how to make a bot it seems. Since we're already using it, we might as well just make the bot for this rather than Slack for now. Transferring the core to other platforms can't be that hard (famous last words)
* There are two user stories that I currently see for this product: (1) for the person setting up the product for others to use, (2) for the people using it.
* (1) Input is settings e.g. base url, how often to re-scrape, default message, language, analytics, etc. Output should be the bot in the form that they choose e.g. RocketChat bot, SlackBot, embeddable web chat, etc.
* (2) Input is question of form text/voice. Output is answer of form text/voice. Because input is text/voice, it could still be hooked up to a phone call. Someone can call, ask a question, and the answer can be played back to them.

**Comment by aubattalia** [comment]
Going off of what David and Julian have mentioned:

- Part of the problem was that if there were too many URLs leading to other URLs in the page then the request would time out.  We either need to find a workaround or find a better way to condense information like that into something easier to parse.

- Input is controlled by text/voice and output can also be text/voice, based off of what amazon does now with their call centers, you can also ask follow up questions using Lex. So on a basic level, our logic for questions should look something like this:
                                 user input stored
                                 if(user input != similarly worded question from FAQ)
                                          {
                                             give error msg and number to call or url of actual faq
                                             store user input or keywords (excludes words like is, that etc.) in database
                                          }
                                  else
                                          {
                                             give verbatim/condensed answer from faq
                                                    somehow answers followup questions or directly has number to call
                                           }
  

- If we do a condensed answer then we'd have to write an algorithm for that 

- Since Amazon Lex is a voice/text UI we can display the whole FAQ answer if it's above a certain character limit on the app.  We could then have Alexa say a condensed version, and then ask if the person would like to see the entire verbatim answer.  If that still doesn't satisfy them they can ask follow up questions.  If that doesn't satisfy them then Alexa could ask if they would like to call the IT center.
